import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Artigos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.className} w-full mx-auto sm:max-w-4xl md:mt-14`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
